// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGather":       schema_pkg_apis_redhatcop_v1alpha1_MustGather(ref),
		"github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherSpec":   schema_pkg_apis_redhatcop_v1alpha1_MustGatherSpec(ref),
		"github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherStatus": schema_pkg_apis_redhatcop_v1alpha1_MustGatherStatus(ref),
	}
}

func schema_pkg_apis_redhatcop_v1alpha1_MustGather(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MustGather is the Schema for the mustgathers API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherSpec", "github.com/redhat-cop/must-gather-operator/pkg/apis/redhatcop/v1alpha1.MustGatherStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_redhatcop_v1alpha1_MustGatherSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MustGatherSpec defines the desired state of MustGather",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_redhatcop_v1alpha1_MustGatherStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MustGatherStatus defines the observed state of MustGather",
				Type:        []string{"object"},
			},
		},
	}
}
